export const data_session = [
  {
    session_name: 'Motivation',
    detail_short: 'Untuk membantu kamu menemukan semangat kembali.',
    detail_full: ['Terkadang rasa lelah dan tekanan membuat semuanya terasa lebih berat dari biasanya. Sesi ini dirancang untuk menemanimu perlahan mengenali kembali tujuan kecil, membangun semangat sedikit demi sedikit, dan memberi jeda dari ramainya pikiran.', 'Tidak perlu terburu-buru. Ikuti setiap langkah sesuai ritmemu sendiri.'],
    icon: '/public/flower-icon/small-icon-1.png',
    total_instruction: 8,
    duration: '20 menit 12 detik',
  },
  {
    session_name: 'Self Reported',
    detail_short: 'Mengenali dan memahami apa yang sedang kamu rasakan.',
    detail_full: ['dummy'],
    icon: '/public/flower-icon/small-icon-2.png',
    total_instruction: 0,
    duration: '0 menit',
  },
  {
    session_name: 'Self Efficacy',
    detail_short: 'Menguatkan kembali rasa percaya terhadap kemampuan diri.',
    detail_full: ['dummy'],
    icon: '/public/flower-icon/small-icon-3.png',
    total_instruction: 0,
    duration: '0 menit',
  },
  {
    session_name: 'Isolation',
    detail_short: 'Menemani saat kamu merasa sendiri dan sulit dipahami orang lain.',
    detail_full: ['dummy'],
    icon: '/public/flower-icon/small-icon-4.png',
    total_instruction: 0,
    duration: '0 menit',
  },
  {
    session_name: 'Time Management',
    detail_short: 'Membantu mengatur waktu agar harimu terasa lebih ringan.',
    detail_full: ['dummy'],
    icon: '/public/flower-icon/small-icon-5.png',
    total_instruction: 0,
    duration: '0 menit',
  },
  {
    session_name: 'Positive Thinking',
    detail_short: 'Membantu melihat sesuatu dengan sudut pandang yang lebih baik.',
    detail_full: ['dummy'],
    icon: '/public/flower-icon/small-icon-6.png',
    total_instruction: 0,
    duration: '0 menit',
  },
  {
    session_name: 'Positive Affection',
    detail_short: 'Menumbuhkan perasaan hangat dan nyaman dalam diri.',
    detail_full: ['dummy'],
    icon: '/public/flower-icon/small-icon-7.png',
    total_instruction: 0,
    duration: '0 menit',
  },
]